# Generated by Django 4.1 on 2024-03-27 14:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("WebApp", "0004_alter_measurement_measurement_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "country_id",
                    models.CharField(
                        help_text="Country ID",
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "country_name",
                    models.CharField(help_text="Country Name", max_length=100),
                ),
                (
                    "country_geometry",
                    models.JSONField(
                        help_text="JSON representation of the country geometry"
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="station",
            name="station_organization",
        ),
        migrations.DeleteModel(
            name="Measurement",
        ),
        migrations.DeleteModel(
            name="Organization",
        ),
        migrations.DeleteModel(
            name="Station",
        ),
    ]
