# Generated by Django 4.1 on 2024-03-27 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("WebApp", "0005_country_remove_station_station_organization_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dzongkhag",
            fields=[
                (
                    "dzongkhag_id",
                    models.CharField(
                        help_text="Dzongkhag ID",
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "dzongkhag_name",
                    models.CharField(help_text="Dzongkhag Name", max_length=100),
                ),
                (
                    "dzongkhag_geometry",
                    models.JSONField(help_text="JSON representation of the dzongkhag"),
                ),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="WebApp.country"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Gewog",
            fields=[
                (
                    "gewog_id",
                    models.CharField(
                        help_text="Gewog ID",
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "gewog_name",
                    models.CharField(help_text="Gewog Name", max_length=100),
                ),
                (
                    "gewog_geometry",
                    models.JSONField(help_text="JSON representation of the gewog"),
                ),
                (
                    "dzongkhag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="WebApp.dzongkhag",
                    ),
                ),
            ],
        ),
    ]
