# Generated by Django 4.1.7 on 2024-04-19 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("WebApp", "0007_datalayer"),
    ]

    operations = [
        migrations.CreateModel(
            name="Temperature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.FloatField()),
                ("year", models.PositiveSmallIntegerField()),
                (
                    "gewog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="WebApp.gewog"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SoilMoisture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.FloatField()),
                ("year", models.PositiveSmallIntegerField()),
                (
                    "gewog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="WebApp.gewog"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RiceDistribution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.FloatField()),
                ("year", models.PositiveSmallIntegerField()),
                (
                    "gewog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="WebApp.gewog"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Precipitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.FloatField()),
                ("year", models.PositiveSmallIntegerField()),
                (
                    "gewog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="WebApp.gewog"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PaddyLoss",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.FloatField()),
                ("year", models.PositiveSmallIntegerField()),
                (
                    "gewog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="WebApp.gewog"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PaddyGain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.FloatField()),
                ("year", models.PositiveSmallIntegerField()),
                (
                    "gewog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="WebApp.gewog"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NDVI",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.FloatField()),
                ("year", models.PositiveSmallIntegerField()),
                (
                    "gewog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="WebApp.gewog"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AverageRice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.FloatField()),
                ("year", models.PositiveSmallIntegerField()),
                (
                    "gewog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="WebApp.gewog"
                    ),
                ),
            ],
        ),
    ]
