# Generated by Django 4.1.7 on 2024-04-25 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("WebApp", "0009_averagerice_dzongkhag_ndvi_dzongkhag_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="averagerice",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="WebApp.country",
            ),
        ),
        migrations.AddField(
            model_name="ndvi",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="WebApp.country",
            ),
        ),
        migrations.AddField(
            model_name="paddygain",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="WebApp.country",
            ),
        ),
        migrations.AddField(
            model_name="paddyloss",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="WebApp.country",
            ),
        ),
        migrations.AddField(
            model_name="precipitation",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="WebApp.country",
            ),
        ),
        migrations.AddField(
            model_name="ricedistribution",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="WebApp.country",
            ),
        ),
        migrations.AddField(
            model_name="soilmoisture",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="WebApp.country",
            ),
        ),
        migrations.AddField(
            model_name="temperature",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="WebApp.country",
            ),
        ),
    ]
