# Generated by Django 4.1.7 on 2024-05-01 17:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("WebApp", "0010_averagerice_country_ndvi_country_paddygain_country_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PaddyGain",
            new_name="PaddyChangeFrom2008",
        ),
        migrations.RenameModel(
            old_name="PaddyLoss",
            new_name="PaddyChangeFrom2020",
        ),
    ]
