# Generated by Django 4.1.7 on 2024-05-01 20:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("WebApp", "0011_rename_paddygain_paddychangefrom2008_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="precipitation",
            name="month",
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True),
        ),
    ]
