# Generated by Django 4.1.7 on 2024-05-05 13:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("WebApp", "0012_precipitation_month"),
    ]

    operations = [
        migrations.AddField(
            model_name="ndvi",
            name="month",
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name="soilmoisture",
            name="month",
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name="temperature",
            name="max",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="temperature",
            name="min",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="temperature",
            name="month",
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True),
        ),
    ]
