# Generated by Django 4.1.7 on 2024-05-07 15:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("WebApp", "0013_ndvi_month_soilmoisture_month_temperature_max_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="temperature",
            name="value",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
