# Generated by Django 4.1.7 on 2024-05-10 14:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("WebApp", "0014_alter_temperature_value"),
    ]

    operations = [
        migrations.AddField(
            model_name="datalayer",
            name="compare_enabled",
            field=models.BooleanField(default=True),
        ),
    ]
