# Generated by Django 4.1.7 on 2024-05-13 15:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("WebApp", "0015_datalayer_compare_enabled"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="RiceDistribution",
            new_name="RiceYield",
        ),
    ]
