# Generated by Django 4.1.7 on 2024-05-14 14:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("WebApp", "0017_riceyield_predicted"),
    ]

    operations = [
        migrations.AddField(
            model_name="datalayer",
            name="display_order",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
