# Generated by Django 4.1.7 on 2024-05-14 17:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("WebApp", "0018_datalayer_display_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="riceyield",
            name="value",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
